version: '3.8'
services:
    postgres:
        image: paradedb/paradedb
        platform: linux/amd64
        restart: always
        environment:
            - POSTGRES_USER=pocpg
            - POSTGRES_PASSWORD=pocpg
            - POSTGRES_DB=pocpg
        ports:
            - '5432:5432'
        volumes:
            - .db:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d
    minio:
        image: quay.io/minio/minio
        platform: linux/amd64
        restart: always
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
            - MINIO_AUDIT_WEBHOOK_ENABLE=true
            - MINIO_AUDIT_WEBHOOK_ENDPOINT=http://echo:8080
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - .minio:/data
        command: server /data --console-address ":9001"
    echo:
        image: daime/http-dump:latest 
        platform: linux/amd64
        ports:
            - "8080:8080"
volumes:
    sql:
    .db:
    .minio:
